---
- hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: Stop service containerd, if started
      service:
        name: containerd
        state: stopped


    - name: uninstall packages 
      apt: 
        pkg:
        - kubectl
        - kubeadm
        - kubelet
        - kubernetes-cni
        - containerd
        state: absent
        allow_change_held_packages: true
        force: true
        purge : true
        autoremove: true

    - name: remove all packages related to kubernetes
      shell: |
              sudo apt remove containerd -f
              sudo rm -fr /etc/kubernetes/; sudo rm -fr ~/.kube/; sudo rm -fr /home/nkorojoseph/.kube/; sudo rm -fr /var/lib/etcd; sudo rm -rf /var/lib/cni/
              sudo systemctl daemon-reload
              sudo iptables -F && sudo iptables -t nat -F && sudo iptables -t mangle -F && sudo iptables -X

#      ignore_errors: true

    - name: remove docker if any
      shell: |
              apt purge -y docker-engine docker docker.io docker-ce docker-ce-cli containerd containerd.io runc --allow-change-held-packages
      ignore_errors: true

    - name: remove parts 
      shell: |
              apt autoremove -y
              rm -rf ~/.kube
              rm -rf /etc/cni /etc/kubernetes /var/lib/dockershim /var/lib/etcd /var/lib/kubelet /var/lib/etcd2/ /var/run/kubernetes ~/.kube/* 
              rm -rf /var/lib/docker /etc/docker /var/run/docker.sock
              rm -f /etc/apparmor.d/docker /etc/systemd/system/etcd*
    - name: clear iptables
      shell: |
              iptables -F && iptables -X
              iptables -t nat -F && iptables -t nat -X
              iptables -t raw -F && iptables -t raw -X
              iptables -t mangle -F && iptables -t mangle -X