- name: turn off swap control
  shell: |
          sudo swapoff -a
          sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Create containerd config file control
  file:
    path: "/etc/modules-load.d/containerd.conf"
    state: "touch"

- name: Add conf for containerd control
  blockinfile:
    path: "/etc/modules-load.d/containerd.conf"
    block: |
          overlay
          br_netfilter

- name: modprobe control
  shell: |
          sudo modprobe overlay
          sudo modprobe br_netfilter

- name: Set system configurations for Kubernetes networking control
  file:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    state: "touch"

- name: Add conf for containerd control
  blockinfile:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply new settings
  command: sudo sysctl --system

- name: install containerd in control
  apt: 
    pkg:
    - containerd.io
    state: latest
    allow_change_held_packages: true
    force: true
    update_cache: true
    
- name: Restart service containerd, in all cases
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: update and install dependencies on conrtol node
  shell: |
          sudo containerd config default | sudo tee /etc/containerd/config.toml

- name: change the systemdcgroup to true on control
  shell: |
          sed -i ' s/\(SystemdCgroup = false\)/\SystemdCgroup = true/g' /etc/containerd/config.toml
          sudo systemctl restart containerd